#pragma once

#include <stack>
#include "../vars/Var.h"
#include "../program/Statement.h"

const int NOT_VALID = -1;

const int semantic_cube[][8][13] = {
	{
		//BOOL BOOL
		//+			-			*			/			%			&&		||			<		>			<=			>=			==		!=
		{NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, NOT_VALID, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//BOOL CHAR
		{NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID},
		//BOOL SHORT
		{NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID},
		//BOOL INT
		{NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID},
		//BOOL LONG
		{NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID},
		//BOOL FLOAT
		{NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID},
		//BOOL DOUBLE
		{NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID},
		//BOOL STRING
		{VARTYPE_STRING, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID}
	},
	{
		//CHAR BOOL
		{NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID},
		//CHAR CHAR
		{VARTYPE_CHAR, VARTYPE_CHAR, VARTYPE_CHAR, VARTYPE_CHAR, VARTYPE_CHAR, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//CHAR SHORT
		{VARTYPE_SHORT, VARTYPE_SHORT, VARTYPE_SHORT, VARTYPE_SHORT, VARTYPE_SHORT, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//CHAR INT
		{VARTYPE_INT, VARTYPE_INT, VARTYPE_INT, VARTYPE_INT, VARTYPE_INT, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//CHAR LONG
		{VARTYPE_LONG, VARTYPE_LONG, VARTYPE_LONG, VARTYPE_LONG, VARTYPE_LONG, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//CHAR FLOAT
		{VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//CHAR DOUBLE
		{VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//CHAR STRING
		{VARTYPE_STRING, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID}
	},
	{
		//SHORT BOOL
		{NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID},
		//SHORT CHAR
		{VARTYPE_SHORT, VARTYPE_SHORT, VARTYPE_SHORT, VARTYPE_SHORT, VARTYPE_SHORT, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//SHORT SHORT
		{VARTYPE_SHORT, VARTYPE_SHORT, VARTYPE_SHORT, VARTYPE_SHORT, VARTYPE_SHORT, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//SHORT INT
		{VARTYPE_INT, VARTYPE_INT, VARTYPE_INT, VARTYPE_INT, VARTYPE_INT, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//SHORT LONG
		{VARTYPE_LONG, VARTYPE_LONG, VARTYPE_LONG, VARTYPE_LONG, VARTYPE_LONG, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//SHORT FLOAT
		{VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//SHORT DOUBLE
		{VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//SHORT STRING
		{VARTYPE_STRING, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID}
	},
	{
		//INT BOOL
		{NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID},
		//INT CHAR
		{VARTYPE_INT, VARTYPE_INT, VARTYPE_INT, VARTYPE_INT, VARTYPE_INT, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//INT SHORT
		{VARTYPE_INT, VARTYPE_INT, VARTYPE_INT, VARTYPE_INT, VARTYPE_INT, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//INT INT
		{VARTYPE_INT, VARTYPE_INT, VARTYPE_INT, VARTYPE_INT, VARTYPE_INT, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//INT LONG
		{VARTYPE_LONG, VARTYPE_LONG, VARTYPE_LONG, VARTYPE_LONG, VARTYPE_LONG, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//INT FLOAT
		{VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//INT DOUBLE
		{VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//INT STRING
		{VARTYPE_STRING, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID}
	},
	{
		//LONG BOOL
		{NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID},
		//LONG CHAR
		{VARTYPE_LONG, VARTYPE_LONG, VARTYPE_LONG, VARTYPE_LONG, VARTYPE_LONG, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//LONG SHORT
		{VARTYPE_LONG, VARTYPE_LONG, VARTYPE_LONG, VARTYPE_LONG, VARTYPE_LONG, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//LONG INT
		{VARTYPE_LONG, VARTYPE_LONG, VARTYPE_LONG, VARTYPE_LONG, VARTYPE_LONG, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//LONG LONG
		{VARTYPE_LONG, VARTYPE_LONG, VARTYPE_LONG, VARTYPE_LONG, VARTYPE_LONG, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//LONG FLOAT
		{VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//LONG DOUBLE
		{VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//LONG STRING
		{VARTYPE_STRING, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID}
	},
	{
		//FLOAT BOOL
		{NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID},
		//FLOAT CHAR
		{VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//FLOAT SHORT
		{VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//FLOAT INT
		{VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//FLOAT LONG
		{VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//FLOAT FLOAT
		{VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, VARTYPE_FLOAT, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//FLOAT DOUBLE
		{VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//FLOAT STRING
		{VARTYPE_STRING, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID}
	},
	{
		//FLOAT BOOL
		{NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID},
		//FLOAT CHAR
		{VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//FLOAT SHORT
		{VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//FLOAT INT
		{VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//FLOAT LONG
		{VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//FLOAT FLOAT
		{VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//FLOAT DOUBLE
		{VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, VARTYPE_DOUBLE, NOT_VALID, NOT_VALID, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL, VARTYPE_BOOL},
		//FLOAT STRING
		{VARTYPE_STRING, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID}
	},
	{
		//STRING BOOL
		{VARTYPE_STRING, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID},
		//STRING CHAR
		{VARTYPE_STRING, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID},
		//STRING SHORT
		{VARTYPE_STRING, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID},
		//STRING INT
		{VARTYPE_STRING, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID},
		//STRING LONG
		{VARTYPE_STRING, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID},
		//STRING FLOAT
		{VARTYPE_STRING, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID},
		//STRING DOUBLE
		{VARTYPE_STRING, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID},
		//STRING STRING
		{VARTYPE_STRING, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID, NOT_VALID}
	}
};

class Aritmetic {
	public:
		Aritmetic();
		std::stack<char> operators;
		std::stack<Var*> operands;
		int isValid(char op, int leftype, int righttype);
};
